# Generated by Django 6.0 on 2026-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=255)),
                ('clean_text', models.TextField()),
                ('ats_score', models.FloatField()),
                ('parse_rate', models.FloatField()),
                ('jd_match', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
